server:
  port: 8080

product:
  name: hello\nworld
  desc: 'hello\nworld'
  details: "hello\nworld"

spring:
  profiles:
    active: dev

---
# https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/howto-properties-and-configuration.html#howto-change-configuration-depending-on-the-environment
spring:
  prifiles: dev

server:
  servlet:
    context-path: /boot-dev

---
spring:
  prifiles:  prod

server:
  servlet:
    context-path: /boot-prod

---
