spring:
  redis:
    cluster:
      nodes: 127.0.0.1:6481,127.0.0.1:6482,127.0.0.1:6483,127.0.0.1:6484,127.0.0.1:6485,127.0.0.1:6486
  
  datasource:
    url: jdbc:mariadb://localhost:3306/ut2
    driverClassName: org.mariadb.jdbc.Driver
    username: user
    password: '123'
    tomcat:
      initSQL: SET NAMES 'utf8mb4'

  security:
    user:
      name: user
      password: '123'

  messages:
    # default basename: messages
    basename: i18n.messages

  profiles:
    active: @activatedProperties@

server:
  port: 8080
  servlet:
    context-path: /boot

product:
  name: hello\nworld
  desc: 'hello\nworld'
  details: "hello\nworld"

# https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
mybatis:
  mapper-locations: classpath:com/example/springboot/dao/mapper/*.xml
  type-aliases-package: com.example.springboot.dao.model
  type-handlers-package: com.example.springboot.dao.mapper
  # configuration:
  #   map-underscore-to-camel-case: true
  #   default-fetch-size: 100
  #   default-statement-timeout: 30

---
# https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/html/howto-properties-and-configuration.html#howto-change-configuration-depending-on-the-environment
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8000
  servlet:
    context-path: /boot-dev

# https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.file-output
logging:
  file: 
  # https://stackoverflow.com/a/61372261/19120213
    path: "${user.home}/logs/"
    # name: boot-app.log
  pattern:
    file: '%d{yyyy-MM-dd hh:mm:ss} [%thread] %X{requestId} %-5level %logger{50} - %msg%n'
    # https://stackoverflow.com/a/42208638/19120213
    # from spring-boot-XXX.RELEASE.jar/org/springframework/boot/logging/logback/defaults.xml
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %X{requestId} %clr(-%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8001
  servlet:
    context-path: /boot-prod

asako:
  id: 3
  name: asako
---
